#!/bin/sh
set -e
cd "$(dirname "$0")/.."

script/bootstrap


./node_modules/.bin/tsc ||:
./node_modules/.bin/browserify -t [ babelify --presets [ es2015 ] ] -o tmp index.js
mv tmp index.js

npm publish
